import {
  Brain, Lightbulb, FileText, Eye, Pencil, Trash2,
  FolderPlus, Search, Terminal, Globe, Rocket,
  CheckCircle, Sparkles, ArrowUp, Database, Wrench,
  RefreshCw, BookOpen, Save, Plug, ImageIcon, Package,
  GitBranch, Key,
  type LucideIcon,
} from 'lucide-react'

export const TOOL_LABELS: Record<string, { label: string; Icon: LucideIcon; color: string }> = {
  think: { label: 'Planning', Icon: Brain, color: 'purple' },
  suggest_improvement: { label: 'Suggestion', Icon: Lightbulb, color: 'yellow' },
  write_file: { label: 'Writing file', Icon: FileText, color: 'green' },
  read_file: { label: 'Reading file', Icon: Eye, color: 'blue' },
  edit_file: { label: 'Editing file', Icon: Pencil, color: 'yellow' },
  delete_file: { label: 'Deleting file', Icon: Trash2, color: 'red' },
  list_files: { label: 'Listing files', Icon: FolderPlus, color: 'blue' },
  search_files: { label: 'Searching files', Icon: Search, color: 'purple' },
  create_project: { label: 'Scaffolding project', Icon: Sparkles, color: 'indigo' },
  github_create_repo: { label: 'Creating GitHub repo', Icon: GitBranch, color: 'green' },
  github_push_update: { label: 'Pushing to GitHub', Icon: ArrowUp, color: 'blue' },
  deploy_to_vercel: { label: 'Deploying to Vercel', Icon: Rocket, color: 'blue' },
  get_all_files: { label: 'File manifest', Icon: Eye, color: 'blue' },
  rename_file: { label: 'Renaming file', Icon: Pencil, color: 'yellow' },
  db_query: { label: 'Querying database', Icon: Database, color: 'green' },
  db_mutate: { label: 'Modifying database', Icon: Database, color: 'yellow' },
  save_project: { label: 'Saving project', Icon: Save, color: 'green' },
  forge_read_own_source: { label: 'Reading own source', Icon: BookOpen, color: 'purple' },
  forge_modify_own_source: { label: 'Self-modifying', Icon: Wrench, color: 'red' },
  forge_redeploy: { label: 'Redeploying self', Icon: RefreshCw, color: 'orange' },
  github_read_file: { label: 'Reading repo file', Icon: Eye, color: 'blue' },
  github_list_repo_files: { label: 'Listing repo files', Icon: FolderPlus, color: 'blue' },
  github_modify_external_file: { label: 'Modifying repo file', Icon: Pencil, color: 'yellow' },
  github_search_code: { label: 'Searching GitHub', Icon: Search, color: 'purple' },
  load_chat_history: { label: 'Loading chat history', Icon: Database, color: 'blue' },
  github_pull_latest: { label: 'Pulling from GitHub', Icon: RefreshCw, color: 'green' },
  mcp_list_servers: { label: 'Listing MCP servers', Icon: Plug, color: 'purple' },
  mcp_connect_server: { label: 'Connecting MCP server', Icon: Plug, color: 'green' },
  mcp_call_tool: { label: 'Calling MCP tool', Icon: Plug, color: 'blue' },
  forge_check_npm_package: { label: 'Checking npm package', Icon: Search, color: 'blue' },
  forge_revert_commit: { label: 'Reverting commit', Icon: RefreshCw, color: 'red' },
  forge_create_branch: { label: 'Creating branch', Icon: GitBranch, color: 'green' },
  forge_create_pr: { label: 'Creating pull request', Icon: GitBranch, color: 'purple' },
  forge_merge_pr: { label: 'Merging pull request', Icon: GitBranch, color: 'green' },
  forge_deployment_status: { label: 'Checking deployment', Icon: Rocket, color: 'blue' },
  forge_check_build: { label: 'Running preview build', Icon: Rocket, color: 'yellow' },
  forge_list_branches: { label: 'Listing branches', Icon: GitBranch, color: 'blue' },
  forge_delete_branch: { label: 'Deleting branch', Icon: GitBranch, color: 'red' },
  forge_read_deploy_log: { label: 'Reading build log', Icon: Terminal, color: 'yellow' },
  db_introspect: { label: 'Inspecting table schema', Icon: Database, color: 'purple' },
  scaffold_component: { label: 'Scaffolding component', Icon: Sparkles, color: 'indigo' },
  generate_env_file: { label: 'Generating .env.example', Icon: FileText, color: 'green' },
  request_env_vars: { label: 'Environment setup', Icon: Key, color: 'amber' },
  start_sandbox: { label: 'Starting sandbox', Icon: Rocket, color: 'green' },
  stop_sandbox: { label: 'Stopping sandbox', Icon: Terminal, color: 'red' },
  sandbox_status: { label: 'Checking sandbox', Icon: Rocket, color: 'blue' },
  add_image: { label: 'Finding image', Icon: ImageIcon, color: 'cyan' },
  check_task_status: { label: 'Checking task', Icon: RefreshCw, color: 'blue' },
  grep_files: { label: 'Grepping files', Icon: BookOpen, color: 'purple' },
  add_dependency: { label: 'Adding package', Icon: Package, color: 'green' },
  validate_file: { label: 'Validating file', Icon: CheckCircle, color: 'green' },
  check_coherence: { label: 'Checking coherence', Icon: Search, color: 'purple' },
  capture_preview: { label: 'Capturing preview', Icon: Eye, color: 'cyan' },
  generate_tests: { label: 'Generating tests', Icon: FileText, color: 'indigo' },
  check_dependency_health: { label: 'Checking package health', Icon: Package, color: 'yellow' },
  search_references: { label: 'Searching references', Icon: BookOpen, color: 'purple' },
  get_reference_code: { label: 'Loading reference', Icon: BookOpen, color: 'blue' },
  save_preference: { label: 'Saving preference', Icon: Save, color: 'green' },
  load_preferences: { label: 'Loading preferences', Icon: Database, color: 'blue' },
  set_custom_domain: { label: 'Setting domain', Icon: Globe, color: 'blue' },
}

export const MODEL_OPTIONS = [
  { id: 'claude-sonnet-4-20250514', label: 'Sonnet 4', description: 'Fast & capable' },
  { id: 'claude-haiku-35-20241022', label: 'Haiku 3.5', description: 'Fastest' },
  { id: 'claude-opus-4-20250514', label: 'Opus 4', description: 'Most capable' },
  { id: 'claude-opus-4-6', label: 'Opus 4.6', description: 'Latest flagship' },
] as const

export const QUICK_ACTIONS = [
  { label: 'Landing Page', query: 'Build a modern landing page with hero section, features grid, testimonials with avatars, pricing table, and footer. Use a cohesive color palette with gradients and animations. Make it look like a real SaaS product.', icon: Sparkles },
  { label: 'Dashboard', query: 'Build an admin dashboard with sidebar navigation, stats cards with sparklines, a chart area, recent activity feed, and a data table with sorting. Dark theme, professional look.', icon: FolderPlus },
  { label: 'Portfolio', query: 'Create a portfolio site with animated hero, project showcase with hover effects, about section with skills, timeline, and a contact form. Minimal, elegant design.', icon: Globe },
  { label: 'E-commerce', query: 'Build an e-commerce product page with image gallery, size/color selector, add to cart, reviews section, and related products. Clean, modern design like Apple Store.', icon: FileText },
]

export const colorClasses: Record<string, string> = {
  green: 'text-emerald-600 bg-emerald-50 dark:text-emerald-400 dark:bg-emerald-950/40',
  blue: 'text-blue-600 bg-blue-50 dark:text-blue-400 dark:bg-blue-950/40',
  yellow: 'text-amber-600 bg-amber-50 dark:text-amber-400 dark:bg-amber-950/40',
  red: 'text-red-600 bg-red-50 dark:text-red-400 dark:bg-red-950/40',
  purple: 'text-purple-600 bg-purple-50 dark:text-purple-400 dark:bg-purple-950/40',
  indigo: 'text-indigo-600 bg-indigo-50 dark:text-indigo-400 dark:bg-indigo-950/40',
  orange: 'text-orange-600 bg-orange-50 dark:text-orange-400 dark:bg-orange-950/40',
  gray: 'text-forge-text-dim bg-forge-surface',
  cyan: 'text-cyan-600 bg-cyan-50 dark:text-cyan-400 dark:bg-cyan-950/40',
  amber: 'text-amber-600 bg-amber-50 dark:text-amber-400 dark:bg-amber-950/40',
}
